package a;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a
 */
public class FrmPPal2 extends javax.swing.JFrame {

    /**
     * Creates new form FrmPPal
     */
    public FrmPPal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEtiquetaConBorde = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        btnEstablecerTextoDeLaEtiqueta = new javax.swing.JButton();
        btnRecuperarTextoDeLaEtiqueta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEtiquetaConBorde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEtiquetaConBorde.setText("Etiqueta con borde");
        lblEtiquetaConBorde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnEstablecerTextoDeLaEtiqueta.setText("Establecer texto de la etiqueta");
        btnEstablecerTextoDeLaEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstablecerTextoDeLaEtiquetaActionPerformed(evt);
            }
        });

        btnRecuperarTextoDeLaEtiqueta.setText("Recuperar texto de la etiqueta");
        btnRecuperarTextoDeLaEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarTextoDeLaEtiquetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEtiquetaConBorde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTexto)
                    .addComponent(btnEstablecerTextoDeLaEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(btnRecuperarTextoDeLaEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblEtiquetaConBorde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstablecerTextoDeLaEtiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecuperarTextoDeLaEtiqueta)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        setBounds(0, 0, 414, 245);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstablecerTextoDeLaEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstablecerTextoDeLaEtiquetaActionPerformed
        // TODO add your handling code here:
        String texto=txtTexto.getText().trim();
        if(texto.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Debe de escribir algo en la caja de texto");
            return;
        }
        lblEtiquetaConBorde.setText(texto);
    }//GEN-LAST:event_btnEstablecerTextoDeLaEtiquetaActionPerformed

    private void btnRecuperarTextoDeLaEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarTextoDeLaEtiquetaActionPerformed
        // TODO add your handling code here:
        String texto=lblEtiquetaConBorde.getText();
        JOptionPane.showMessageDialog(this, texto);
    }//GEN-LAST:event_btnRecuperarTextoDeLaEtiquetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPPal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstablecerTextoDeLaEtiqueta;
    private javax.swing.JButton btnRecuperarTextoDeLaEtiqueta;
    private javax.swing.JLabel lblEtiquetaConBorde;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
